/* This file is automatically generated */

#ifndef __BINWARE_H__
#define __BINWARE_H__

#ifndef __BINWARE_STRUCT__
#define __BINWARE_STRUCT__

typedef struct
{
	const char*		name;
	int			size;
	const unsigned char*	data;
} binware_s;

#endif // __BINWARE_STRUCT__

extern binware_s binware_pogoshell [];
extern binware_s binware_f2a_loader_pro [];
extern binware_s binware_f2a_loader_ultra [];
extern binware_s binware_f2a_usb_firmware [];
extern binware_s binware_f2a_multiboot [];
extern binware_s binware_f2a_splash [];
extern binware_s binware_f2a_usb_writer_firmware [];
extern binware_s binware_efa_loader [];
extern binware_s binware_efa_usb_firmware [];

#endif // __BINWARE_H__
